before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly

build:
  script:
    - cargo build --release

test:
  script:
  - cargo test --lib
  - bash examples/run_examples.sh
