before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly

build:
  script:
    - cargo build

test:
  script:
  - source "$HOME/.cargo/env"
  - cargo test --lib
  - bash examples/run_examples.sh
