before_script:
  - apt-get update -qq
  - apt-get install -qq build-essential curl git
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
  - source "$HOME/.cargo/env"

nightly:
  script:
    - cargo build
    - cargo test --lib
    - cargo test --manifest-path ion_braces/Cargo.toml
    - cargo test --manifest-path ion_builtins/Cargo.toml
    - cargo test --manifest-path ion_ranges/Cargo.toml
    - bash examples/run_examples.sh
