language: rust
rust:
  - nightly
sudo: false
before_script:
  - cargo install rustfmt --root . --debug
  - cp -r src formatted
  - ./bin/rustfmt --write-mode=overwrite formatted/*
script:
  - cargo build --verbose
  - cargo test --verbose
  - diff --brief -r src formatted/
notifications:
  email: false
