[package]
name = "ion-shell"
description = "The Ion Shell"
repository = "https://github.com/redox-os/ion"
version = "1.0.5"
license-file = "LICENSE"
readme = "README.md"
authors = [
  "Michael Aaron Murphy <mmstickman@gmail.com>",
  "Hunter Goldstein <hunter.d.goldstein@gmail.com>",
  "Skyler Berg <skylertheberg@gmail.com>",
  "Jeremy Soller <jackpot51@gmail.com>",
  "Michael Gattozzi <mgattozzi@gmail.com>",
  "Łukasz Niemier <lukasz@niemier.pl>",
]
build = "build.rs"

[[bin]]
name = "ion"
path = "src/main.rs"

## Shared Dependencies

[dependencies]
# Provides XDG app directory support
app_dirs = "1.1.1"
# Provides methods for bitwise flag operations
bitflags = "0.9.1"
# Provides inline arithmetic expression and `calc` functionality
calculate = "0.1"
# A faster hashing algorithm for the hash maps in the shell.
fnv = "1.0"
# Performs globbing on words that are detected to be potentially globbable.
glob = "0.2"
# Provides a macro for lazily-evalulated statics
lazy_static = "0.2"
# Provides the line editor / prompt for the shell
liner = { git = "https://github.com/MovingtoMars/liner/" }
# Provides permutations of strings in brace expansions
permutate = "0.3"
# Enables strings to be stored inline on the stack, when possible.
smallstring = "0.1"
# Same as the above, but for vectors.
smallvec = "0.4"
# Provides grapheme-based string iterators.
unicode-segmentation = "1.2"

## Redox Dependencies

[target.'cfg(target_os = "redox")'.dependencies]
# Provides access to Redox syscalls for signals/job control.
redox_syscall = "0.1"

## *nix Dependencies (Linux, Mac OS, BSDs)

[target.'cfg(all(unix, not(target_os = "redox")))'.dependencies]
# Used by `tokio-signal`/`tokio-core` for creating zero-allocation streams of future data.
futures = "0.1"
# Required to access some *nix-specific syscalls for signals/job control.
libc = "0.2"
# A higher level abstraction of libc-acquired syscalls for signals/job control.
nix = "0.8"
# Provides the core event loop for a tokio solution.
tokio-core = "0.1"
# Provides a high level abstraction to watching signals with tokio.
tokio-signal = "0.1"
# Obtains user directories
users = "0.5.1"

[replace]
"bytecount:0.1.6" = { git = "https://github.com/llogiq/bytecount", revision = "ea6fb86dfaeb838d22a2feae618d1df7f1b3ce0d" }

[build-dependencies]
ansi_term = "0.9"
peg = "0.5"
version_check = "0.1.3"

[profile.release]
# debug = true
# rustflags = [ "-C", "target-cpu=native"]
lto = true
panic = "abort"
