[package]
name = "ion-shell"
description = "The Ion Shell"
repository = "https://github.com/redox-os/ion"
version = "0.0.3"
license-file = "LICENSE"
readme = "README.md"
authors = [
  "Jeremy Soller <jackpot51@gmail.com>",
  "Michael Gattozzi <mgattozzi@gmail.com>",
  "Łukasz Niemier <lukasz@niemier.pl>"
]
