[package]

authors = [
    "Michael Aaron Murphy <mmstickman@gmail.com>",
    "Hunter Goldstein <hunter.d.goldstein@gmail.com>",
    "Skyler Berg <skylertheberg@gmail.com>",
    "Jeremy Soller <jackpot51@gmail.com>",
    "Michael Gattozzi <mgattozzi@gmail.com>",
    "Łukasz Niemier <lukasz@niemier.pl>",
]
build = "build.rs"
description = "The Ion Shell"
license-file = "LICENSE"
name = "ion-shell"
readme = "README.md"
repository = "https://gitlab.redox-os.org/redox-os/ion"
version = "1.0.0-alpha"

[workspace]
members = [ "ion_braces", "ion_builtins", "ion_sys", "ion_ranges" ]

[[bin]]
name = "ion"
path = "src/main.rs"

[build-dependencies]
ansi_term = "0.11"
version_check = "0.1.3"

[dependencies]
bitflags = "1.0"
calculate = "0.5"
failure = "0.1"
failure_derive = "0.1"
fnv = "1.0"
glob = "0.2"
itoa = "0.4"
lazy_static = "1.0"
liner = { git = "https://gitlab.redox-os.org/redox-os/liner" }
rand = "0.5"
regex = "1.0"
smallstring = "0.1"
smallvec = "0.6"
unicode-segmentation = "1.2"
xdg = { git = "https://github.com/whitequark/rust-xdg" }
ion_braces = { path = "ion_braces" }
ion_builtins = { path = "ion_builtins" }
ion_sys = { path = "ion_sys" }
ion_ranges = { path = "ion_ranges" }

[lib]
path = "src/lib/lib.rs"

[profile.release]
lto = true
panic = "abort"

[target."cfg(all(unix, not(target_os = \"redox\")))".dependencies]
libloading = "0.5"

[patch.crates-io]
liner = { git = "https://gitlab.redox-os.org/redox-os/liner" }
