error_on_line_overflow = false
max_width = 120
fn_call_width = 80
fn_single_line = true
write_mode = "overwrite"
where_style = "legacy"
condense_wildcard_suffixes = true
imports_indent = "Block"
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 80
struct_field_align_threshold = 30

