condense_wildcard_suffixes = true
error_on_line_overflow = false
fn_call_width = 80
fn_single_line = true
imports_indent = "Block"
max_width = 100
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
single_line_if_else_max_width = 80
struct_field_align_threshold = 30
trailing_semicolon = false
where_style = "legacy"
write_mode = "overwrite"
