[package]
name = "ion_braces"
version = "0.1.0"
authors = ["Michael Murphy <mmstickman@gmail.com>"]
edition = "2018"

[dependencies]
permutate = "0.3"
smallvec = "0.6"
small = { git = "https://gitlab.redox-os.org/redox-os/small", features = ["std"] }
auto_enums = "0.5.5"
