name: Build
on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      task:
        description: "Build binary for aarch64"
        required: true
        type: boolean

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Replace software sources with the latest
      run: |
        # 删除原有的软件源
        sudo rm -f /etc/apt/sources.list

        # 添加最新的 Ubuntu 24.04 (Noble Numbat) 官方软件源
        echo "deb http://archive.ubuntu.com/ubuntu/ noble main restricted universe multiverse" | sudo tee /etc/apt/sources.list
        echo "deb http://archive.ubuntu.com/ubuntu/ noble-updates main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb http://archive.ubuntu.com/ubuntu/ noble-security main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
        echo "deb http://archive.ubuntu.com/ubuntu/ noble-backports main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list

    - name: Add Ubuntu GPG key
      run: |
        # 添加 Ubuntu 官方 GPG 密钥
        curl -fsSL http://archive.ubuntu.com/ubuntu/project/ubuntu-archive-keyring.gpg | sudo gpg --dearmour -o /etc/apt/trusted.gpg.d/ubuntu.gpg

    - name: Set up LLVM APT repository
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl
        
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-19 main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain.list
        # wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        # echo "deb http://apt.llvm.org/$(lsb_release -cs)/llvm-toolchain-$(lsb_release -cs)-$(date +%Y%m)/ main" | sudo tee /etc/apt/sources.list.d/llvm-toolchain.list
        sudo apt-get update
        sudo apt-get autoremove
        sudo apt-get install clang-19 llvm-19 musl-tools musl musl-dev build-essential pkg-config cmake libssl-dev zlib1g-dev libsqlite3-dev protobuf-compiler libffi7
        
    - name: Setup environment
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup-init.sh
        chmod 777 rustup-init.sh
        ./rustup-init.sh --help
        bash rustup-init.sh -y --default-toolchain nightly
        rustup target add aarch64-unknown-linux-musl --toolchain=nightly
        
    - name: Check compiler
      run: |
        clang -v
        clang-19 -v
        
    - name: Build
      run: |
        export CC_aarch64_unknown_linux_musl=clang-19
        export AR_aarch64_unknown_linux_musl=llvm-ar
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS="-Clink-self-contained=yes -Clinker=rust-lld"
        
        export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=ld.lld
        export CC=clang-19
        export CXX=clang++-19
        CC=clang-19 cargo build --target aarch64-unknown-linux-musl --release

    - name: Check info
      run: |
        ls -ltrah
        ls -ltrah target/aarch64-unknown-linux-musl/release/
        tree

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        path: target/aarch64-unknown-linux-musl/release/ion

    
    
   
