name: Update Dependencies

on:
  workflow_dispatch:

permissions: write-all

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Update dependencies
      run: |
        cargo install cargo-edit
        cargo upgrade --latest

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add Cargo.toml Cargo.lock
        git commit -m "Update dependencies"
        git push origin master
        
