name: llvm
on:
  workflow_dispatch:
    inputs:
      task:
        description: "Download and cache llvm"
        required: true
        type: boolean
permissions: write-all
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup llvm
      run: |
        wget "https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.5/LLVM-19.1.5-Linux-X64.tar.xz"
        tar -xf LLVM-19.1.5-Linux-X64.tar.xz
        rm LLVM-19.1.5-Linux-X64.tar.xz
        
    - name: Cache llvm
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add LLVM-19.1.5-Linux-X64
        git commit -m "Cache llvm" || echo "No changes to commit"
        git push origin main
